var importantItems = [
  'Bow',
  'Progressive Hookshot',
  'Megaton Hammer',
  'Slingshot',
  'Boomerang',
  'Bomb Bag',
  'Lens of Truth',
  'Dins Fire',
  'Farores Wind',
  'Nayrus Love',
  'Fire Arrows',
  'Ice Arrows',
  'Light Arrows',
  'Fairy Ocarina',
  'Ocarina of Time',
  'Ocarina',
  'Bottle',
  'Rutos Letter',
  'Bottle with Milk',
  'Bottle with Red Potion',
  'Bottle with Green Potion',
  'Bottle with Blue Potion',
  'Bottle with Fairy',
  'Bottle with Fish',
  'Bottle with Blue Fire',
  'Bottle with Bugs',
  'Bottle with Poe',
  'Weird Egg',
  'Pocket Egg',
  'Pocket Cucco',
  'Cojiro',
  'Odd Mushroom',
  'Odd Potion',
  'Poachers Saw',
  'Broken Sword',
  'Prescription',
  'Eyeball Frog',
  'Eyedrops',
  'Claim Check',
  'Kokiri Sword',
  'Master Sword',
  'Biggoron Sword',
  'Mirror Shield',
  'Goron Tunic',
  'Zora Tunic',
  'Iron Boots',
  'Hover Boots',
  'Progressive Strength Upgrade',
  'Progressive Scale',
  'Progressive Wallet',
  'Magic Meter',
  'Stone of Agony',
  'Bombchus (5)',
  'Bombchus (10)',
  'Bombchus (20)',
  'Bombchus',
  'Magic Bean',
  'Boss Key',
  'Small Key',
  'Boss Key (Forest Temple)',
  'Boss Key (Fire Temple)',
  'Boss Key (Water Temple)',
  'Boss Key (Spirit Temple)',
  'Boss Key (Shadow Temple)',
  'Boss Key (Ganons Castle)',
  'Small Key (Forest Temple)',
  'Small Key (Fire Temple)',
  'Small Key (Water Temple)',
  'Small Key (Spirit Temple)',
  'Small Key (Shadow Temple)',
  'Small Key (Bottom of the Well)',
  'Small Key (Gerudo Training Ground)',
  'Small Key (Gerudo Fortress)',
  'Small Key (Ganons Castle)',
  'Zeldas Letter',
  'Zeldas Lullaby',
  'Eponas Song',
  'Suns Song',
  'Sarias Song',
  'Song of Time',
  'Song of Storms',
  'Minuet of Forest',
  'Prelude of Light',
  'Bolero of Fire',
  'Serenade of Water',
  'Nocturne of Shadow',
  'Requiem of Spirit',
  'Gold Skulltulla Token',
  'Epona',
  'Gerudo Membership Card',
  'Forest Trial Clear',
  'Fire Trial Clear',
  'Water Trial Clear',
  'Shadow Trial Clear',
  'Spirit Trial Clear',
  'Light Trial Clear',
  'Triforce',
];

var majorItems = [
  'Bow',
  'Progressive Hookshot',
  'Megaton Hammer',
  'Slingshot',
  'Boomerang',
  'Bomb Bag',
  'Lens of Truth',
  'Dins Fire',
  'Farores Wind',
  'Nayrus Love',
  'Fire Arrows',
  'Ice Arrows',
  'Blue Fire Arrows',
  'Light Arrows',
  'Fairy Ocarina',
  'Ocarina of Time',
  'Ocarina',
  'Bottle',
  'Rutos Letter',
  'Bottle with Milk',
  'Bottle with Red Potion',
  'Bottle with Green Potion',
  'Bottle with Blue Potion',
  'Bottle with Fairy',
  'Bottle with Fish',
  'Bottle with Blue Fire',
  'Bottle with Bugs',
  'Bottle with Poe',
  'Weird Egg',
  'Pocket Egg',
  'Pocket Cucco',
  'Cojiro',
  'Odd Mushroom',
  'Odd Potion',
  'Poachers Saw',
  'Broken Sword',
  'Prescription',
  'Eyeball Frog',
  'Eyedrops',
  'Claim Check',
  'Kokiri Sword',
  'Master Sword',
  'Biggoron Sword',
  'Mirror Shield',
  'Goron Tunic',
  'Zora Tunic',
  'Iron Boots',
  'Hover Boots',
  'Progressive Strength Upgrade',
  'Progressive Scale',
  'Progressive Wallet',
  'Magic Meter',
  'Stone of Agony',
  'Magic Bean',
  'Zeldas Letter',
  'Zeldas Lullaby',
  'Eponas Song',
  'Suns Song',
  'Sarias Song',
  'Song of Time',
  'Song of Storms',
  'Minuet of Forest',
  'Prelude of Light',
  'Bolero of Fire',
  'Serenade of Water',
  'Nocturne of Shadow',
  'Requiem of Spirit',
  'Epona',
  'Gerudo Membership Card',
  'Triforce',
];

var inSpoilerExceptions = ['Check Pedestal (Stones)', 'Check Pedestal (Medallions)', 'Light Arrows Hint', 'Ganon'];

hashImages = {
    'Deku Stick': 'stick.png',
    'Deku Nut': 'nut.png',
    'Bow': 'bow.png',
    'Slingshot': 'slingshot.png',
    'Fairy Ocarina': 'fairyocarina.png',
    'Bombchu': 'bombchu.png',
    'Longshot': 'longshot.png',
    'Boomerang': 'boomerang.png',
    'Lens of Truth': 'lens.png',
    'Beans': 'bean.png',
    'Megaton Hammer': 'hammer.png',
    'Bottled Fish': 'fish.png',
    'Bottled Milk': 'milk.png',
    'Mask of Truth': 'truth.png',
    'SOLD OUT': 'soldout.png',
    'Cucco': 'cucco.png',
    'Mushroom': 'mushroom.png',
    'Saw': 'saw.png',
    'Frog': 'frog.png',
    'Master Sword': 'sword2.png',
    'Mirror Shield': 'shield3.png',
    'Kokiri Tunic': 'greentunic.png',
    'Hover Boots': 'hoverboots.png',
    'Silver Gauntlets': 'lift2.png',
    'Gold Scale': 'scale2.png',
    'Stone of Agony': 'agony.png',
    'Skull Token': 'skulltula.png',
    'Heart Container': 'heartcontainer.png',
    'Boss Key': 'boss_key.png',
    'Compass': 'compass.png',
    'Map': 'map.png',
    'Big Magic': 'magic2.png',
  };

  var itemFreestandingImages = {
    'Bow': "bow.png",
    'Progressive Hookshot': "hookshot.png",
    'Megaton Hammer': "hammer.png",
    'Slingshot': "slingshot.png",
    'Boomerang': "boomerang.png",
    'Bomb Bag': "bombbag.png",
    'Lens of Truth': "lens.png",
    'Dins Fire': "din.png",
    'Farores Wind': "farore.png",
    'Nayrus Love': "nayru.png",
    'Fire Arrows': "firearrow.png",
    'Ice Arrows': "icearrow.png",
    'Blue Fire Arrows': "icearrow.png",
    'Light Arrows': "lightarrow.png",
    'Fairy Ocarina': "ocarina.png",
    'Ocarina of Time': "ocarina.png",
    'Ocarina': "ocarina.png",
    'Bottle': "bottle0.png",
    'Rutos Letter': "ruto.png",
    'Bottle with Milk': "milk.png",
    'Bottle with Red Potion': "redpotion.png",
    'Bottle with Green Potion': "greenpotion.png",
    'Bottle with Blue Potion': "bluepotion.png",
    'Bottle with Fairy': "fairy.png",
    'Bottle with Fish': "fish.png",
    'Bottle with Blue Fire': "bluefire.png",
    'Bottle with Bugs': "bug.png",
    'Bottle with Poe': "poe.png",
    'Bottle with Big Poe': "bigpoe.png",
    'Weird Egg': "egg.png",
    'Pocket Egg': "egg.png",
    'Pocket Cucco': "cucco.png",
    'Cojiro': "cojiro.png",
    'Odd Mushroom': "mushroom.png",
    'Odd Potion': "medicine.png",
    'Poachers Saw': "saw.png",
    'Broken Sword': "broken_sword.png",
    'Prescription': "prescription.png",
    'Eyeball Frog': "frog.png",
    'Eyedrops': "eyedrops.png",
    'Claim Check': "claim.png",
    'Kokiri Sword': "sword1.png",
    'Master Sword': "sword2.png",
    'Biggoron Sword': "sword3.png",
    'Deku Shield': "shield1.png",
    'Hylian Shield': "shield2.png",
    'Mirror Shield': "shield3.png",
    'Goron Tunic': "redtunic.png",
    'Zora Tunic': "besttunic.png",
    'Iron Boots': "ironboots.png",
    'Hover Boots': "hoverboots.png",
    'Progressive Strength Upgrade': "lift1.png",
    'Progressive Scale': "scale1.png",
    'Progressive Wallet': "wallet.png",
    'Magic Meter': "magic.png",
    'Stone of Agony': "agony.png",
    'Bombchus (5)': "bombchu.png",
    'Bombchus (10)': "bombchu.png",
    'Bombchus (20)': "bombchu.png",
    'Bombchus': "bombchu.png",
    'Magic Bean': "bean.png",
    'Boss Key': "boss_key.png",
    'Small Key': "small_key.png",
    'Key Ring': "small_key.png",
    'Boss Key (Forest Temple)': "boss_key.png",
    'Boss Key (Fire Temple)': "boss_key.png",
    'Boss Key (Water Temple)': "boss_key.png",
    'Boss Key (Spirit Temple)': "boss_key.png",
    'Boss Key (Shadow Temple)': "boss_key.png",
    'Boss Key (Ganons Castle)': "boss_key.png",
    'Small Key (Forest Temple)': "small_key.png",
    'Small Key (Fire Temple)': "small_key.png",
    'Small Key (Water Temple)': "small_key.png",
    'Small Key (Spirit Temple)': "small_key.png",
    'Small Key (Shadow Temple)': "small_key.png",
    'Small Key (Bottom of the Well)': "small_key.png",
    'Small Key (Gerudo Training Ground)': "small_key.png",
    'Small Key (Gerudo Fortress)': "small_key.png",
    'Small Key (Ganons Castle)': "small_key.png",
    'Small Key Ring (Forest Temple)': "small_key.png",
    'Small Key Ring (Fire Temple)': "small_key.png",
    'Small Key Ring (Water Temple)': "small_key.png",
    'Small Key Ring (Spirit Temple)': "small_key.png",
    'Small Key Ring (Shadow Temple)': "small_key.png",
    'Small Key Ring (Bottom of the Well)': "small_key.png",
    'Small Key Ring (Gerudo Training Ground)': "small_key.png",
    'Small Key Ring (Gerudo Fortress)': "small_key.png",
    'Small Key Ring (Ganons Castle)': "small_key.png",
    'Zeldas Letter': "letter.png",
    'Zeldas Lullaby': "zelda.png",
    'Eponas Song': "epona.png",
    'Suns Song': "sunsong.png",
    'Sarias Song': "saria.png",
    'Song of Time': "songoftime.png",
    'Song of Storms': "songofstorms.png",
    'Minuet of Forest': "green_note.png",
    'Prelude of Light': "yellow_note.png",
    'Bolero of Fire': "red_note.png",
    'Serenade of Water': "blue_note.png",
    'Nocturne of Shadow': "purple_note.png",
    'Requiem of Spirit': "orange_note.png",
    'Gold Skulltula Token': "token.png",
    'Epona': "epona.png",
    'Gerudo Membership Card': "gerudo-card_32x32.png",
    'Triforce': "triforce_32x32.png",
    'Heart Container': "heartcontainermodel.png",
    'Heart Piece': "heartcontainermodel.png",
    'Piece of Heart': "heartcontainermodel.png",
  };
  
var hintItemsMeanings = {
  "mystic training": "Magic Meter",
  "pixie dust": "Magic Meter",
  "a green rectangle": "Magic Meter",
  "a Magic Meter": "Magic Meter",
  "a white outline": "Double Defense",
  "damage decrease": "Double Defense",
  "strengthened love": "Double Defense",
  "Double Defense": "Double Defense",
  "a seed shooter": "Slingshot",
  "a rubberband": "Slingshot",
  "a child's catapult": "Slingshot",
  "a Slingshot": "Slingshot",
  "a banana": "Boomerang",
  "a stun stick": "Boomerang",
  "the Boomerang": "Boomerang",
  "an archery enabler": "Bow",
  "a danger dart launcher": "Bow",
  "a Bow": "Bow",
  "an explosive container": "Bomb Bag",
  "a blast bag": "Bomb Bag",
  "a Bomb Bag": "Bomb Bag",
  "Dampe's keepsake": "Progressive Hookshot",
  "the Grapple Beam": "Progressive Hookshot",
  "the BOING! chain": "Progressive Hookshot",
  "a Hookshot": "Progressive Hookshot",
  "power gloves": "Progressive Strength Upgrade",
  "metal mittens": "Progressive Strength Upgrade",
  "the heavy lifty": "Progressive Strength Upgrade",
  "a Strength Upgrade": "Progressive Strength Upgrade",
  "a deeper dive": "Progressive Scale",
  "a piece of Zora": "Progressive Scale",
  "a Zora Scale": "Progressive Scale",
  "the dragon smasher": "Megaton Hammer",
  "the metal mallet": "Megaton Hammer",
  "the heavy hitter": "Megaton Hammer",
  "the Megaton Hammer": "Megaton Hammer",
  "sink shoes": "Iron Boots",
  "clank cleats": "Iron Boots",
  "the Iron Boots": "Iron Boots",
  "butter boots": "Hover Boots",
  "sacred slippers": "Hover Boots",
  "spacewalkers": "Hover Boots",
  "the Hover Boots": "Hover Boots",
  "a butter knife": "Kokiri Sword",
  "a starter slasher": "Kokiri Sword",
  "a switchblade": "Kokiri Sword",
  "the Kokiri Sword": "Kokiri Sword",
  "the biggest blade": "Biggoron Sword",
  "a colossal cleaver": "Biggoron Sword",
  "the Biggoron Sword": "Biggoron Sword",
  "evil's bane": "Master Sword",
  "the Master Sword": "Master Sword",
  "a wooden ward": "Deku Shield",
  "a burnable barrier": "Deku Shield",
  "a Deku Shield": "Deku Shield",
  "a steel safeguard": "Hylian Shield",
  "Like Like's metal meal": "Hylian Shield",
  "a Hylian Shield": "Hylian Shield",
  "the reflective rampart": "Mirror Shield",
  "Medusa's weakness": "Mirror Shield",
  "a silvered surface": "Mirror Shield",
  "the Mirror Shield": "Mirror Shield",
  "teleportation": "Farores Wind",
  "a relocation rune": "Farores Wind",
  "a green ball": "Farores Wind",
  "a green gust": "Farores Wind",
  "Farore's Wind": "Farores Wind",
  "a safe space": "Nayrus Love",
  "an impregnable aura": "Nayrus Love",
  "a blue barrier": "Nayrus Love",
  "a blue crystal": "Nayrus Love",
  "Nayru's Love": "Nayrus Love",
  "an inferno": "Dins Fire",
  "a heat wave": "Dins Fire",
  "a red ball": "Dins Fire",
  "Din's Fire": "Dins Fire",
  "the furnace firearm": "Fire Arrows",
  "the burning bolts": "Fire Arrows",
  "a magma missile": "Fire Arrows",
  "the Fire Arrows": "Fire Arrows",
  "the refrigerator rocket": "Ice Arrows",
  "the frostbite bolts": "Ice Arrows",
  "an iceberg maker": "Ice Arrows",
  "the Ice Arrows": "Ice Arrows",
  "the shining shot": "Light Arrows",
  "the luminous launcher": "Light Arrows",
  "Ganondorf's bane": "Light Arrows",
  "the lighting bolts": "Light Arrows",
  "the Light Arrows": "Light Arrows",
  "a lie detector": "Lens of Truth",
  "a ghost tracker": "Lens of Truth",
  "true sight": "Lens of Truth",
  "a detective's tool": "Lens of Truth",
  "the Lens of Truth": "Lens of Truth",
  "a flute": "Ocarina",
  "a music maker": "Ocarina",
  "an Ocarina": "Ocarina",
  "ruby robes": "Goron Tunic",
  "fireproof fabric": "Goron Tunic",
  "cooking clothes": "Goron Tunic",
  "a Goron Tunic": "Goron Tunic",
  "a sapphire suit": "Zora Tunic",
  "scuba gear": "Zora Tunic",
  "a swimsuit": "Zora Tunic",
  "a Zora Tunic": "Zora Tunic",
  "a horse": "Epona",
  "a four legged friend": "Epona",
  "Epona": "Epona",
  "a song of royal slumber": "Zeldas Lullaby",
  "a triforce tune": "Zeldas Lullaby",
  "Zelda's Lullaby": "Zeldas Lullaby",
  "an equestrian etude": "Eponas Song",
  "Malon's melody": "Eponas Song",
  "a ranch song": "Eponas Song",
  "Epona's Song": "Eponas Song",
  "a song of dancing Gorons": "Sarias Song",
  "Saria's phone number": "Sarias Song",
  "Saria's Song": "Sarias Song",
  "Sunny Day": "Suns Song",
  "the ReDead's bane": "Suns Song",
  "the Gibdo's bane": "Suns Song",
  "the Sun's Song": "Suns Song",
  "a song 7 years long": "Song of Time",
  "the tune of ages": "Song of Time",
  "the Song of Time": "Song of Time",
  "Rain Dance": "Song of Storms",
  "a thunderstorm tune": "Song of Storms",
  "windmill acceleration": "Song of Storms",
  "the Song of Storms": "Song of Storms",
  "the song of tall trees": "Minuet of Forest",
  "an arboreal anthem": "Minuet of Forest",
  "a green spark trail": "Minuet of Forest",
  "the Minuet of Forest": "Minuet of Forest",
  "a song of lethal lava": "Bolero of Fire",
  "a red spark trail": "Bolero of Fire",
  "a volcanic verse": "Bolero of Fire",
  "the Bolero of Fire": "Bolero of Fire",
  "a song of a damp ditch": "Serenade of Water",
  "a blue spark trail": "Serenade of Water",
  "the lake's lyric": "Serenade of Water",
  "the Serenade of Water": "Serenade of Water",
  "a song of sandy statues": "Requiem of Spirit",
  "an orange spark trail": "Requiem of Spirit",
  "the desert ditty": "Requiem of Spirit",
  "the Requiem of Spirit": "Requiem of Spirit",
  "a song of spooky spirits": "Nocturne of Shadow",
  "a graveyard boogie": "Nocturne of Shadow",
  "a haunted hymn": "Nocturne of Shadow",
  "a purple spark trail": "Nocturne of Shadow",
  "the Nocturne of Shadow": "Nocturne of Shadow",
  "a luminous prologue melody": "Prelude of Light",
  "a yellow spark trail": "Prelude of Light",
  "the temple traveler": "Prelude of Light",
  "the Prelude of Light": "Prelude of Light",
  "a glass container": "Bottle",
  "an empty jar": "Bottle",
  "encased air": "Bottle",
  "a Bottle": "Bottle",
  "a call for help": "Rutos Letter",
  "the note that Mweeps": "Rutos Letter",
  "an SOS call": "Rutos Letter",
  "a fishy stationery": "Rutos Letter",
  "Ruto's Letter": "Rutos Letter",
  "cow juice": "Bottle with Milk",
  "a white liquid": "Bottle with Milk",
  "a baby's breakfast": "Bottle with Milk",
  "a Milk Bottle": "Bottle with Milk",
  "a vitality vial": "Bottle with Red Potion",
  "a red liquid": "Bottle with Red Potion",
  "a Red Potion Bottle": "Bottle with Red Potion",
  "a magic mixture": "Bottle with Green Potion",
  "a green liquid": "Bottle with Green Potion",
  "a Green Potion Bottle": "Bottle with Green Potion",
  "an ailment antidote": "Bottle with Blue Potion",
  "a blue liquid": "Bottle with Blue Potion",
  "a Blue Potion Bottle": "Bottle with Blue Potion",
  "an imprisoned fairy": "Bottle with Fairy",
  "an extra life": "Bottle with Fairy",
  "Navi's cousin": "Bottle with Fairy",
  "a Fairy Bottle": "Bottle with Fairy",
  "an aquarium": "Bottle with Fish",
  "a deity's snack": "Bottle with Fish",
  "a Fish Bottle": "Bottle with Fish",
  "a conflagration canteen": "Bottle with Blue Fire",
  "an icemelt jar": "Bottle with Blue Fire",
  "a Blue Fire Bottle": "Bottle with Blue Fire",
  "an insectarium": "Bottle with Bugs",
  "Skulltula finders": "Bottle with Bugs",
  "a Bug Bottle": "Bottle with Bugs",
  "a spooky ghost": "Bottle with Poe",
  "a face in the jar": "Bottle with Poe",
  "a Poe Bottle": "Bottle with Poe",
  "the spookiest ghost": "Bottle with Big Poe",
  "a sidequest spirit": "Bottle with Big Poe",
  "a Big Poe Bottle": "Bottle with Big Poe",
  "the shake stone": "Stone of Agony",
  "the Rumble Pak (TM)": "Stone of Agony",
  "the Stone of Agony": "Stone of Agony",
  "a girl club membership": "Gerudo Membership Card",
  "a desert tribe's pass": "Gerudo Membership Card",
  "the Gerudo Card": "Gerudo Membership Card",
  "a mo' money holder": "Progressive Wallet",
  "a gem purse": "Progressive Wallet",
  "a portable bank": "Progressive Wallet",
  "a Wallet": "Progressive Wallet",
  "a lumber rack": "Deku Stick Capacity",
  "more flammable twigs": "Deku Stick Capacity",
  "Deku Stick Capacity": "Deku Stick Capacity",
  "more nuts": "Deku Nut Capacity",
  "flashbang storage": "Deku Nut Capacity",
  "Deku Nut Capacity": "Deku Nut Capacity",
  "a lot of love": "Heart Container",
  "a Valentine's gift": "Heart Container",
  "a boss's organ": "Heart Container",
  "a Heart Container": "Heart Container",
  "a little love": "Piece of Heart",
  "a broken heart": "Piece of Heart",
  "a Piece of Heart": "Piece of Heart",
  "a victory valentine": "Piece of Heart (Treasure Chest Game)",
  "a free heal": "Recovery Heart",
  "a hearty meal": "Recovery Heart",
  "a Band-Aid": "Recovery Heart",
  "a Recovery Heart": "Recovery Heart",
  "the dollar of defeat": "Rupee (Treasure Chest Game)",
  "a breakable branch": "Deku Stick (1)",
  "a Deku Stick": "Deku Stick (1)",
  "a unique coin": "Rupee (1)",
  "a penny": "Rupee (1)",
  "a green gem": "Rupee (1)",
  "a Green Rupee": "Rupee (1)",
  "a common coin": "Rupees (5)",
  "a blue gem": "Rupees (5)",
  "a Blue Rupee": "Rupees (5)",
  "couch cash": "Rupees (20)",
  "a red gem": "Rupees (20)",
  "a Red Rupee": "Rupees (20)",
  "big bucks": "Rupees (50)",
  "a purple gem": "Rupees (50)",
  "wealth": "Rupees (50)",
  "a Purple Rupee": "Rupees (50)",
  "a juicy jackpot": "Rupees (200)",
  "a yellow gem": "Rupees (200)",
  "a giant gem": "Rupees (200)",
  "great wealth": "Rupees (200)",
  "a Huge Rupee": "Rupees (200)",
  "a chicken dilemma": "Weird Egg",
  "the Weird Egg": "Weird Egg",
  "an autograph": "Zeldas Letter",
  "royal stationery": "Zeldas Letter",
  "royal snail mail": "Zeldas Letter",
  "Zelda's Letter": "Zeldas Letter",
  "a Cucco container": "Pocket Egg",
  "a Cucco, eventually": "Pocket Egg",
  "a fowl youth": "Pocket Egg",
  "the Pocket Egg": "Pocket Egg",
  "a little clucker": "Pocket Cucco",
  "the Pocket Cucco": "Pocket Cucco",
  "a cerulean capon": "Cojiro",
  "Cojiro": "Cojiro",
  "a powder ingredient": "Odd Mushroom",
  "an Odd Mushroom": "Odd Mushroom",
  "Granny's goodies": "Odd Potion",
  "an Odd Potion": "Odd Potion",
  "a tree killer": "Poachers Saw",
  "the Poacher's Saw": "Poachers Saw",
  "a shattered slicer": "Broken Sword",
  "the Broken Sword": "Broken Sword",
  "a pill pamphlet": "Prescription",
  "a doctor's note": "Prescription",
  "the Prescription": "Prescription",
  "a perceiving polliwog": "Eyeball Frog",
  "the Eyeball Frog": "Eyeball Frog",
  "a vision vial": "Eyedrops",
  "the Eyedrops": "Eyedrops",
  "a three day wait": "Claim Check",
  "the Claim Check": "Claim Check",
  "a dungeon atlas": "Map",
  "blueprints": "Map",
  "a Map": "Map",
  "a treasure tracker": "Compass",
  "a magnetic needle": "Compass",
  "a Compass": "Compass",
  "a master of unlocking": "Boss Key",
  "a dungeon's master pass": "Boss Key",
  "a Boss Key": "BossKey",
  "a tool for unlocking": "Small Key",
  "a dungeon pass": "Small Key",
  "a lock remover": "Small Key",
  "a lockpick": "Small Key",
  "a Small Key": "Small Key",
  "a get out of jail free card": "FortressSmallKey",
  "a Jail Key": "FortressSmallKey",
  "something mysterious": "KeyError",
  "an unknown treasure": "KeyError",
  "An Error (Please Report This)": "KeyError",
  "a few danger darts": "Arrows (5)",
  "a few sharp shafts": "Arrows (5)",
  "Arrows (5 pieces)": "Arrows (5)",
  "some danger darts": "Arrows (10)",
  "some sharp shafts": "Arrows (10)",
  "Arrows (10 pieces)": "Arrows (10)",
  "plenty of danger darts": "Arrows (30)",
  "plenty of sharp shafts": "Arrows (30)",
  "Arrows (30 pieces)": "Arrows (30)",
  "a few explosives": "Bombs (5)",
  "a few blast balls": "Bombs (5)",
  "Bombs (5 pieces)": "Bombs (5)",
  "some explosives": "Bombs (10)",
  "some blast balls": "Bombs (10)",
  "Bombs (10 pieces)": "Bombs (10)",
  "lots-o-explosives": "Bombs (20)",
  "plenty of blast balls": "Bombs (20)",
  "Bombs (20 pieces)": "Bombs (20)",
  "a gift from Ganon": "Ice Trap",
  "a chilling discovery": "Ice Trap",
  "frosty fun": "Ice Trap",
  "an Ice Trap": "Ice Trap",
  "wizardly legumes": "Magic Bean",
  "a Magic Bean": "Magic Bean",
  "mice bombs": "Bombchus",
  "proximity mice": "Bombchus",
  "wall crawlers": "Bombchus",
  "trail blazers": "Bombchus",
  "Bombchus": "Bombchus",
  "a few mice bombs": "Bombchus (5)",
  "a few proximity mice": "Bombchus (5)",
  "a few wall crawlers": "Bombchus (5)",
  "a few trail blazers": "Bombchus (5)",
  "Bombchus (5 pieces)": "Bombchus (5)",
  "some mice bombs": "Bombchus (10)",
  "some proximity mice": "Bombchus (10)",
  "some wall crawlers": "Bombchus (10)",
  "some trail blazers": "Bombchus (10)",
  "Bombchus (10 pieces)": "Bombchus (10)",
  "plenty of mice bombs": "Bombchus (20)",
  "plenty of proximity mice": "Bombchus (20)",
  "plenty of wall crawlers": "Bombchus (20)",
  "plenty of trail blazers": "Bombchus (20)",
  "Bombchus (20 pieces)": "Bombchus (20)",
  "some nuts": "Deku Nuts (5)",
  "some flashbangs": "Deku Nuts (5)",
  "some scrub spit": "Deku Nuts (5)",
  "Deku Nuts (5 pieces)": "Deku Nuts (5)",
  "lots-o-nuts": "Deku Nuts (10)",
  "plenty of flashbangs": "Deku Nuts (10)",
  "plenty of scrub spit": "Deku Nuts (10)",
  "Deku Nuts (10 pieces)": "Deku Nuts (10)",
  "catapult ammo": "Deku Seeds (30)",
  "lots-o-seeds": "Deku Seeds (30)",
  "Deku Seeds (30 pieces)": "Deku Seeds (30)",
  "proof of destruction": "Gold Skulltula Token",
  "an arachnid chip": "Gold Skulltula Token",
  "spider remains": "Gold Skulltula Token",
  "one percent of a curse": "Gold Skulltula Token",
  "a Gold Skulltula Token": "Gold Skulltula Token",
  "is a foolish choice": "Foolish Choice",
  "way of the hero": "Way of the Hero",
  "path to Queen Gohma": "Path to Queen Gohma",
  "path to King Dodongo": "Path to King Dodongo",
  "path to Barinade": "Path to Barinade",
  "path to Phantom Ganon": "Path to Phantom Ganon",
  "path to Volvagia": "Path to Volvagia",
  "path to Morpha": "Path to Morpha",
  "path to Bongo Bongo": "Path to Bongo Bongo",
  "path to Twinrova": "Path to Twinrova",
};

var hintLocationsMeanings = {
  "a lone scrub in Death Mountain Crater sells": "DMC Deku Scrub",
  "a single scrub in the crater sells": "DMC Deku Scrub",
  "a spider under a crate in the crater holds": "DMC GS Crate",
  "showing the Claim Check to Biggoron rewards": "DMT Biggoron",
  "Biggoron crafts": "DMT Biggoron",
  "Darunia's dance leads to": "GC Darunias Joy",
  "in Goron City the hammer unlocks": "GC Maze Left Chest",
  "spinning Goron pottery contains": "GC Pot Freestanding PoH",
  "the Goron Pot's happy face spits out": "GC Pot Freestanding PoH",
  "mastery of horseback archery grants": "GF HBA 1500 Points",
  "scoring 1500 in horseback archery grants": "GF HBA 1500 Points",
  "playing Sun's Song in a grave spawns": "Graveyard Heart Piece Grave Chest",
  "the Composer Brothers hid": "Graveyard Royal Familys Tomb Chest",
  "flames in the royal tomb reveal": "Graveyard Royal Familys Tomb Chest",
  "lighting flames in the royal tomb rewards": "Graveyard Royal Familys Tomb Chest",
  "in Gerudo Valley the hammer unlocks": "GV Chest",
  "a cow in Gerudo Valley gifts": "GV Cow",
  "the fairy of fire holds": "HC Great Fairy Reward",
  "a fairy outside Hyrule Castle holds": "HC Great Fairy Reward",
  "a spider behind a muddy wall in a grotto holds": "HC GS Storms Grotto",
  "the cobwebbed cow gifts": "HF Cow Grotto Cow",
  "a cow behind webs in a grotto gifts": "HF Cow Grotto Cow",
  "a spider behind webs in a grotto holds": "HF GS Cow Grotto",
  "the treasure thrown by Princess Zelda is": "HF Ocarina of Time Item",
  "slaying 20 Gold Skulltulas reveals": "Kak 20 Gold Skulltula Reward",
  "slaying 30 Gold Skulltulas reveals": "Kak 30 Gold Skulltula Reward",
  "slaying 40 Gold Skulltulas reveals": "Kak 40 Gold Skulltula Reward",
  "slaying 50 Gold Skulltulas reveals": "Kak 50 Gold Skulltula Reward",
  "chucking chickens gifts": "Kak Anju as Child",
  "collecting cuccos rewards": "Kak Anju as Child",
  "the bovine bounty of a horseback hustle gifts": "KF Links House Cow",
  "Malon's obstacle course leads to": "KF Links House Cow",
  "a diving experiment is rewarded with": "LH Lab Dive",
  "a lakeside lab diving experiment rewards": "LH Lab Dive",
  "staring into the sun grants": "LH Sun",
  "shooting the sun grants": "LH Sun",
  "the Skull Kid grants": "LW Skull Kid",
  "shooting a target in the woods grants": "LW Target in Woods",
  "the Skull Mask yields": "Deku Theater Skull Mask",
  "wearing the Skull Mask in the Deku Theater rewards": "Deku Theater Skull Mask",
  "showing a truthful eye to the crowd rewards": "Deku Theater Mask of Truth",
  "showing the Mask of Truth in the Deku Theater rewards": "Deku Theater Mask of Truth",
  "catching Big Poes leads to": "Market 10 Big Poes",
  "ghost hunters will be rewarded with": "Market 10 Big Poes",
  "gambling in the market grants": "Market Treasure Chest Game Reward",
  "there is a 1/32 chance to win": "Market Treasure Chest Game Reward",
  "winning the treasure chest game rewards": "Market Treasure Chest Game Reward",
  "a fairy outside Ganon's Castle holds": "OGC Great Fairy Reward",
  "the fairy of strength holds": "OGC Great Fairy Reward",
  "deep in the wasteland is": "Wasteland Chest",
  "beneath the sands, flames reveal": "Wasteland Chest",
  "the Haunted Wasteland torches reveal": "Wasteland Chest",
  "a spider in the wasteland holds": "Wasteland GS",
  "unfreezing King Zora grants": "ZD King Zora Thawed",
  "a defrosted dignitary gifts": "ZD King Zora Thawed",
  "under the icy waters lies": "ZF Bottom Freestanding PoH",
  "at the bottom of Zora's Fountain lies": "ZF Bottom Freestanding PoH",
  "a spider high above the icy waters holds": "ZF GS Hidden Cave",
  "frogs in a storm gift": "ZR Frogs in the Rain",
  "playing Song of Storms to Frogs rewards": "ZR Frogs in the Rain",
  "an amphibian feast yields": "ZR Frog Ocarina Game",
  "the croaking choir's magnum opus awards": "ZR Frogs Ocarina Game",
  "the froggy finale yields": "ZR Frogs Ocarina Game",
  "the final reward from the Frogs of Zora's River is": "ZR Frogs Ocarina Game",
  "a temporal stone within a tree contains": "Deku Tree MQ After Spinning Log Chest",
  "a temporal stone within the Deku Tree contains": "Deku Tree MQ After Spinning Log Chest",
  "a spider on a ceiling in a tree holds": "Deku Tree MQ GS Basement Graves Room",
  "a spider on a ceiling in the Deku Tree holds": "Deku Tree MQ GS Basement Graves Room",
  "a spider under temporal stones in Dodongo's Cavern holds": "Dodongos Cavern MQ GS Song of Time Block Room",
  "a spider under temporal stones in a cavern holds": "Dodongos Cavern MQ GS Song of Time Block Room",
  "a school of stingers swallowed by a deity guard": "Jabu Jabus Belly Boomerang Chest",
  "a school of stingers swallowed by Jabu Jabu guard": "Jabu Jabus Belly Boomerang Chest",
  "a cow swallowed by Jabu Jabu gifts": "Jabu Jabus Belly MQ Cow",
  "a cow swallowed by a deity gifts": "Jabu Jabus Belly MQ Cow",
  "a spider surrounded by shadows in Jabu Jabu's Belly holds": "Jabu Jabus Belly MQ GS Invisible Enemies Room",
  "a spider surrounded by shadows in the belly of a deity holds": "Jabu Jabus Belly MQ GS Invisible Enemies Room",
  "the Flare Dancer atop the volcano guards a chest containing": "Fire Temple Megaton Hammer Chest / Fire Temple MQ Chest On Fire",
  "the Flare Dancer atop the Fire Temple guards a chest containing": "Fire Temple Megaton Hammer Chest / Fire Temple MQ Chest On Fire",
  "Pierre atop the Fire Temple hides": "Fire Temple Scarecrow Chest",
  "a scarecrow atop the volcano hides": "Fire Temple Scarecrow Chest",
  "a spider under a block in the volcano holds": "Fire Temple MQ GS Skull On Fire",
  "a spider under a block in the Fire Temple holds": "Fire Temple MQ GS Skull On Fire",
  "beyond the river in the Water Temple waits": "Water Temple River Chest",
  "beyond the river under the lake waits": "Water Temple River Chest",
  "dodging rolling boulders under the lake leads to": "Water Temple Boss Key Chest / Water Temple MQ Boss Key Chest",
  "dodging rolling boulders in the Water Temple leads to": "Water Temple Boss Key Chest / Water Temple MQ Boss Key Chest",
  "a spider behind a gate in the Water Temple holds": "Water Temple MQ GS Triple Wall Torch",
  "a spider behind a gate under the lake holds": "Water Temple MQ GS Triple Wall Torch",
  "the locked spider in the Water Temple holds": "Water Temple MQ GS Freestanding Key Area",
  "hidden in a box in the Water Temple lies": "Water Temple MQ Freestanding Key",
  "hidden in a box under the lake lies": "Water Temple MQ Freestanding Key",
  "the locked spider under the lake holds": "Water Temple MQ GS Freestanding Key Area",
  "a chest in the central pillar of Water Temple contains": "Water Temple MQ Central Pillar Chest",
  "beneath a tall tower under a vast lake lies": "Water Temple MQ Central Pillar Chest",
  "the treasure sought by Nabooru is": "Spirit Temple Silver Gauntlets Chest",
  "upon the Colossus's right hand is": "Spirit Temple Silver Gauntlets Chest",
  "upon the Colossus's left hand is": "Spirit Temple Mirror Shield Chest",
  "a spider's symphony in the Spirit Temple yields": "Spirit Temple MQ GS Symphony Room",
  "a temporal paradox in the Spirit Temple yields": "Spirit Temple MQ Child Hammer Switch Chest",
  "a temporal paradox in the Colossus yields": "Spirit Temple MQ Child Hammer Switch Chest",
  "a symphony in the Colossus yields": "Spirit Temple MQ Symphony Room Chest",
  "a symphony in the Spirit Temple yields": "Spirit Temple MQ Symphony Room Chest",
  "a spider's symphony in the Colossus yields": "Spirit Temple MQ GS Symphony Room",
  "a burning skull in the house of the dead holds": "Shadow Temple Freestanding Key",
  "a giant pot in the Shadow Temple holds": "Shadow Temple Freestanding Key",
  "a grasping ghoul surrounded by Bomb Flowers guards": "Shadow Temple MQ Bomb Flower Chest",
  "the Dead Hand surrounded by Bomb Flowers guards": "Shadow Temple MQ Bomb Flower Chest",
  "stalfos in the Shadow Temple guard": "Shadow Temple MQ Stalfos Room Chest",
  "near an empty pedestal within the house of the dead lies": "Shadow Temple MQ Stalfos Room Chest",
  "those who seek sunken silver rupees will find": "Gerudo Training Ground Underwater Silver Rupee Chest / Gerudo Training Ground MQ Underwater Silver Rupee Chest",
  "obtaining the underwater silver rupees in Gerudo Training Ground rewards": "Gerudo Training Ground MQ Underwater Silver Rupee Chest",
  "Gerudo Training Ground final reward contains": "Gerudo Training Ground Maze Path Final Chest / Gerudo Training Ground MQ Ice Arrows Chest",
  "the final prize of the thieves' training is": "Gerudo Training Ground MQ Ice Arrows Chest",
  "the thieves' underwater training rewards": "Gerudo Training Ground MQ Underwater Silver Rupee Chest",
  "a monster in a frozen cavern guards": "Ice Cavern MQ Iron Boots Chest",
  "the final treasure of Ice Cavern is": "Ice Cavern MQ Iron Boots Chest",
  "a like-like in Ganon's Shadow Trial guards": "Ganons Castle Shadow Trial Golden Gauntlets Chest",
  "shooting an eye switch in Ganon's Shadow Trial reveals": "Ganons Castle MQ Shadow Trial Eye Switch Chest",
  "deep in the test of darkness lies": "Ganons Castle MQ Shadow Trial Eye Switch Chest",
  "the song taught by the Ocarina of Time is": "Song from Ocarina of Time",
  "the Ocarina of Time teaches": "Song from Ocarina of Time",
  "the Composer Brothers wrote": "Song from Royal Familys Tomb",
  "the song written in the royal tomb is": "Song from Royal Familys Tomb",
  "ReDead in the royal tomb guard": "Song from Royal Familys Tomb",
  "in the Sacred Forest Meadow, Sheik teaches": "Sheik in Forest",
  "in a meadow Sheik teaches": "Sheik in Forest",
  "Sheik waits at a monument to time to teach": "Sheik at Temple",
  "the Temple of Time chimes with the music of": "Sheik at Temple",
  "the crater's melody is": "Sheik in Crater",
  "Sheik waits in the Death Mountain Crater to teach": "Sheik in Crater",
  "the frozen cavern echoes with": "Sheik in Ice Cavern",
  "the Ice Cavern corridors ring with": "Sheik in Ice Cavern",
  "a ravaged village mourns with": "Sheik in Kakariko",
  "amidst flames in Kakariko Village, Sheik gives": "Sheik in Kakariko",
  "a hero ventures beyond the wasteland to learn": "Sheik at Colossus",
  "the Desert Colossus sands echo with": "Sheik at Colossus",
  'an ancient tree': 'Deku Tree',
  'Deku Tree': 'Deku Tree',
  "the Deku Tree": "Deku Tree",
  'an immense cavern': 'Dodongos Cavern',
  'Dodongo\'s Cavern': 'Dodongos Cavern',
  "Dodongo's Cavern": "Dodongos Cavern",
  'the belly of a deity': 'Jabu Jabus Belly',
  'Jabu Jabu\'s Belly': 'Jabu Jabus Belly',
  "Jabu Jabu's Belly": "Jabu Jabus Belly",
  'a deep forest': 'Forest Temple',
  'Forest Temple': 'Forest Temple',
  "the Forest Temple": "Forest Temple",
  'a high mountain': 'Fire Temple',
  'Fire Temple': 'Fire Temple',
  "the Fire Temple": "Fire Temple",
  'a vast lake': 'Water Temple',
  'Water Temple': 'Water Temple',
  "the Water Temple": "Water Temple",
  'the house of the dead': 'Shadow Temple',
  'Shadow Temple': 'Shadow Temple',
  "the Shadow Temple": "Shadow Temple",
  'the goddess of the sand': 'Spirit Temple',
  'Spirit Temple': 'Spirit Temple',
  "the Spirit Temple": "Spirit Temple",
  'a frozen maze': 'Ice Cavern',
  'Ice Cavern': 'Ice Cavern',
  "the Ice Cavern": "Ice Cavern",
  'a shadow\'s prison': 'Bottom of the Well',
  'Bottom of the Well': 'Bottom of the Well',
  "the Bottom of the Well": "Bottom of the Well",
  'the test of thieves': 'Gerudo Training Ground',
  'Gerudo Training Ground': 'Gerudo Training Ground',
  "the Gerudo Training Ground": "Gerudo Training Ground",
  'outside Ganon\'s Castle': 'Outside Ganon\'s Castle',
  'a conquered citadel': 'Ganon\'s Castle',
  'Ganon\'s Castle': 'Ganon\'s Castle',
  "inside Ganon's Castle": "Ganons Castle",
  'Death Mountain Trail': 'Death Mountain Trail',
  'Graveyard': 'Graveyard',
  'Goron City': 'Goron City',
  'Lost Woods': 'Lost Woods',
  'Temple of Time': 'Temple of Time',
  'Haunted Wasteland': 'Haunted Wasteland',
  'Desert Colossus': 'Desert Colossus',
  'Lost Woods': 'Lost Woods',
  'Kokiri Forest': 'Kokiri Forest',
  'Death Mountain Crater': 'Death Mountain Crater',
  'Desert Colossus': 'Desert Colossus',
  'Lon Lon Ranch': 'Lon Lon Ranch',
  'Sacred Forest Meadow': 'Sacred Forest Meadow',
  'Gerudo\'s Fortress': 'Gerudo Fortress',
  'Kakariko Village': 'Kakariko Village',
  'Market': 'Market',
  'Gerudo Valley': 'Gerudo Valley',
  'Lake Hylia': 'Lake Hylia',
  'Zora\'s River': 'Zora\'s River',
  'Zora\'s Domain': 'Zora\'s Domain',
  'Zora\'s Fountain': 'Zora\'s Fountain',
  'Hyrule Castle': 'Hyrule Castle',
  'Hyrule Field': 'Hyrule Field',
};

var warpSongs = ['Minuet of Forest', 'Bolero of Fire', 'Serenade of Water', 'Nocturne of Shadow', 'Requiem of Spirit', 'Prelude of Light'];

var songTargets = {
  'Minuet of Forest': 'Sacred Forest Meadow',
  'Bolero of Fire': 'Death Mountain Crater',
  'Serenade of Water': 'Lake Hylia',
  'Nocturne of Shadow': 'Above Graveyard',
  'Requiem of Spirit': 'Desert Colossus',
  'Prelude of Light': 'Temple of Time'
}

var dungeons = [
  'Deku Tree',
  'Dodongos Cavern',
  'Jabu Jabus Belly',
  'Forest Temple',
  'Fire Temple',
  'Water Temple',
  'Spirit Temple',
  'Shadow Temple',
  'Ice Cavern',
  'Bottom of the Well',
  'Gerudo Training Ground',
  'Ganon\'s Castle'
]

var dungeonSmallKeyCount = {
  'Forest Temple': 5,
  'Fire Temple': 8,
  'Water Temple': 6,
  'Shadow Temple': 5,
  'Spirit Temple': 5,
  'Bottom of the Well': 3,
  'Gerudo Training Ground': 9,
  'Gerudo Fortress': 4,
  'Ganons Castle': 2
}

var bosses = {
  'Links Pocket': 'Free',
  'Queen Gohma': 'Deku Tree',
  'King Dodongo': 'Dodongos Cavern',
  'Barinade': 'Jabu Jabus Belly',
  'Phantom Ganon': 'Forest Temple',
  'Volvagia': 'Fire Temple',
  'Morpha': 'Water Temple',
  'Bongo Bongo': 'Shadow Temple',
  'Twinrova': 'Spirit Temple'
};

var regionChangingChecks = {
  'Impa at Castle': 'Hyrule Field',
  'Queen Gohma': 'Kokiri Forest',
  'King Dodongo': 'Death Mountain Trail',
  'Barinade': 'Zoras Fountain',
  'Phantom Ganon': 'Kokiri Forest',
  'Volvagia': 'Death Mountain Crater',
  'Morpha': 'Lake Hylia',
  'Bongo Bongo': 'Above Graveyard',
  'Twinrova': 'Desert Colossus',
};

var entrancesByRegionChild = {
  'LW Bridge From Forest': ['Kokiri Forest', 'Hyrule Field'],
  'Kokiri Forest': ['Deku Tree', 'Lost Woods', 'Hyrule Field'],
  'Deku Tree': ['Kokiri Forest'],
  'Lost Woods': ['Kokiri Forest', 'Goron City', 'Zora River', 'Sacred Forest Meadow'],
  'Sacred Forest Meadow': ['Lost Woods'],
  'Hyrule Field': ['Kokiri Forest', 'Market', 'Kakariko Village', 'Zora River', 'Lon Lon Ranch', 'Gerudo Valley', 'Lake Hylia'],
  'Market': ['Hyrule Field', 'Temple of Time', 'Hyrule Castle'],
  'Temple of Time': ['Market', 'Pull Master Sword'],
  'Hyrule Castle': ['Market'],
  'Lon Lon Ranch': ['Hyrule Field'],
  'Lake Hylia': ['Hyrule Field', 'Zoras Domain'],
  'Gerudo Valley': ['Hyrule Field', 'Lake Hylia'],
  'Gerudo Fortress': ['Gerudo Valley'],
  'Desert Colossus': ['Spirit Temple', 'Haunted Wasteland'],
  'Haunted Wasteland': ['Desert Colossus'],
  'Spirit Temple': ['Desert Colossus'],
  'Kakariko Village': ['Hyrule Field', 'Bottom of the Well', 'Death Mountain Trail', 'Graveyard'],
  'Bottom of the Well': ['Kakariko Village'],
  'Above Graveyard': ['Graveyard'],
  'Graveyard': ['Kakariko Village'],
  'Death Mountain Trail': ['Death Mountain Crater', 'Goron City', 'Kakariko Village', 'Dodongos Cavern'],
  'Death Mountain Crater': ['Death Mountain Trail'],
  'Goron City': ['Lost Woods', 'Death Mountain Trail'],
  'Dodongos Cavern': ['Death Mountain Trail'],
  'Zora River': ['Zoras Domain', 'Lost Woods', 'Hyrule Field'],
  'Zoras Domain': ['Zoras Fountain', 'Zora River', 'Lake Hylia'],
  'Zoras Fountain': ['Zoras Domain', 'Jabu Jabus Belly'],
  'Jabu Jabus Belly': ['Zoras Fountain'],
};

var gossipStonesByRegionChild = {
    'Death Mountain Crater': ['Bombable Wall'],
    'Death Mountain Trail': ['Biggoron'],
    'Desert Colossus': ['Spirit Temple'],
    'Dodongos Cavern': ['Bombable Wall'],
    'Gerudo Valley': ['Waterfall'],
    'Goron City': ['Maze', 'Medigoron'],
    'Above Graveyard': ['Shadow Temple'],
    'Hyrule Castle': ['Malon', 'Rock Wall'],
    'Kokiri Forest': ['Deku Tree Left', 'Deku Tree Right'],
    'Lake Hylia': ['Lab', 'Southeast Corner', 'Southwest Corner'],
    'Lost Woods': ['Bridge'],
    'Sacred Forest Meadow': ['Maze Lower', 'Maze Upper', 'Saria'],
    'Temple of Time': ['Left', 'Left-Center', 'Right', 'Right-Center'],
    'Zoras Domain': ['Mweep'],
    'Zoras Fountain': ['Fairy', 'Jabu'],
    'Zoras River': ['Plateau', 'Waterfall'],
};

var entrancesByRegionAdult = {
  'Kokiri Forest': ['Lost Woods', 'Hyrule Field'],
  'Lost Woods': ['Kokiri Forest', 'Sacred Forest Meadow', 'Goron City', 'Zora River'],
  'Sacred Forest Meadow': ['Forest Temple', 'Lost Woods'],
  'Forest Temple': ['Sacred Forest Meadow'],
  'Hyrule Field': ['Kokiri Forest', 'Market', 'Kakariko Village', 'Zora River', 'Lon Lon Ranch', 'Gerudo Valley', 'Lake Hylia'],
  'Market': ['Hyrule Field', 'Temple of Time', 'Outside Ganons Castle'],
  'Temple of Time': ['Market', 'Place Master Sword'],
  'Lon Lon Ranch': ['Hyrule Field'],
  'Lake Hylia': ['Hyrule Field', 'Water Temple'],
  'Water Temple': ['Lake Hylia'],
  'Gerudo Valley': ['Hyrule Field', 'Lake Hylia', 'Gerudo Fortress'],
  'Gerudo Fortress': ['Haunted Wasteland', 'Gerudo Valley', 'Gerudo Training Ground'],
  'Gerudo Training Ground': ['Gerudo Fortress'],
  'Haunted Wasteland': ['Gerudo Fortress', 'Desert Colossus'],
  'Desert Colossus': ['Spirit Temple', 'Haunted Wasteland'],
  'Spirit Temple': ['Desert Colossus'],
  'Kakariko Village': ['Hyrule Field', 'Death Mountain Trail', 'Graveyard'],
  'Graveyard': ['Kakariko Village'],
  'Above Graveyard': ['Shadow Temple', 'Graveyard'],
  'Shadow Temple': ['Above Graveyard'],
  'Death Mountain Trail': ['Death Mountain Crater', 'Goron City', 'Kakariko Village', 'Dodongos Cavern'],
  'Death Mountain Crater': ['Death Mountain Trail', 'Fire Temple', 'Goron City'],
  'Fire Temple': ['Death Mountain Crater'],
  'Goron City': ['Lost Woods', 'Death Mountain Trail', 'Death Mountain Crater'],
  'Dodongos Cavern': ['Death Mountain Trail'],
  'Zora River': ['Zoras Domain', 'Lost Woods', 'Hyrule Field'],
  'Zoras Domain': ['Zoras Fountain', 'Zora River'],
  'Zoras Fountain': ['Zoras Domain', 'Ice Cavern'],
  'Ice Cavern': ['Zoras Fountain'],
  'Outside Ganons Castle': ['Ganons Castle', 'Market'],
  'Ganons Castle': ['Outside Ganons Castle']
};

var utilityByRegionAdult = {};

var gossipStonesByRegionAdult = {
    'Death Mountain Crater': ['Bombable Wall'],
    'Death Mountain Trail': ['Biggoron', 'Storms Grotto'],
    'Desert Colossus': ['Spirit Temple'],
    'Dodongos Cavern': ['Bombable Wall'],
    'Gerudo Valley': ['Waterfall'],
    'Goron City': ['Maze', 'Medigoron'],
    'Above Graveyard': ['Shadow Temple'],
    'Hyrule Castle': ['Malon', 'Rock Wall'],
    'Kokiri Forest': ['Deku Tree Left', 'Deku Tree Right'],
    'Lake Hylia': ['Lab', 'Southeast Corner', 'Southwest Corner'],
    'Lost Woods': ['Bridge'],
    'Sacred Forest Meadow': ['Maze Lower', 'Maze Upper', 'Saria'],
    'Temple of Time': ['Left', 'Left-Center', 'Right', 'Right-Center'],
    'Zoras Domain': ['Mweep'],
    'Zoras Fountain': ['Fairy', 'Jabu'],
    'Zoras River': ['Plateau', 'Waterfall'],
};

// Need to add certain spawns to other maps for logical reasons, add a line saying where the spawn is so players can know the checks they can get?.
var spawnsByRegion = {
    "Kokiri Forest":                 ['Kokiri Forest', 'KF Midos House', 'KF Sarias House', 'KF House of Twins', 'KF Know It All House', 'KF Kokiri Shop', 'KF Links House'],
    "LW Bridge From Forest":         ['LW Bridge From Forest', 'LW Bridge'],
    "Lost Woods":                    ['Lost Woods', 'LW Beyond Mido', 'LW Forest Exit', 'Deku Theater'],
    "Goron City":                    ['GC Woods Warp', 'GC Darunias Chamber', 'Goron City', 'GC Shop'],
    "Zora River":                    ['Zora River', 'ZR Behind Waterfall', 'ZR Front'],
    "Sacred Forest Meadow":          ['SFM Entryway', 'SFM Wolfos Grotto', 'SFM Fairy Grotto'],
    "Hyrule Field":                  ['Hyrule Field'],
    "Lake Hylia":                    ['Lake Hylia', 'LH Lab', 'LH Fishing Hole', 'LH Fishing Island'],
    "Gerudo Valley":                 ['Gerudo Valley', 'GV Fortress Side'],
    "Market":                        ['Market', 'Market Entrance', 'Market Mask Shop', 'Market Guard House', 'Market Bombchu Bowling', 'Market Potion Shop', 'Market Treasure Chest Game',
                                     'Market Bombchu Shop', 'Market Man in Green House', 'Market Shooting Gallery', 'Market Bazaar'],
    "Kakariko Village":              ['Kakariko Village', 'Kak Behind Gate', 'Kak Impas Ledge', 'Kak Potion Shop Front', 'Kak Potion Shop Back', 'Kak Carpenter Boss House',
                                     'Kak House of Skulltula', 'Kak Impas House', 'Kak Impas House Back', 'Kak Odd Medicine Building', 'Kak Shooting Gallery', 'Kak Windmill', 
                                     'Kak Bazaar', 'Kak Redead Grotto', 'Kak Backyard'],
    "Lon Lon Ranch":                 ['Lon Lon Ranch', 'LLR Talons House', 'LLR Stables', 'LLR Tower'],
    "Zoras Domain":                  ['Zoras Domain', 'ZD Behind King Zora', 'ZD Shop'],
    "Gerudo Fortress":               ['Gerudo Fortress', 'GF Outside Gate', 'GV Carpenter Tent'],
    "Haunted Wasteland":             ['Wasteland Near Fortress', 'Wasteland Near Colossus'],
    "Desert Colossus":               ['Desert Colossus', 'Colossus Great Fairy Fountain'],
    "Hyrule Castle":                 ['Castle Grounds', 'HC Great Fairy Fountain'],
    "Temple of Time":                ['ToT Entrance', 'Temple of Time'],
    "Graveyard":                     ['Graveyard', 'Graveyard Dampes House', 'Graveyard Royal Familys Tomb', 'Graveyard Dampes Grave', 'Graveyard Shield Grave', 'Graveyard Heart Piece Grave'],
    "Death Mountain Trail":          ['Death Mountain', 'Death Mountain Summit', 'DMT Great Fairy Fountain'],
    "Death Mountain Crater":         ['DMC Lower Local', 'DMC Lower Nearby', 'DMC Upper Local', 'DMC Upper Nearby', 'DMC Great Fairy Fountain'],
    "Zoras Fountain":                ['Zoras Fountain', 'ZF Great Fairy Fountain'],
    "Outside Ganons Castle":         ['OGC Great Fairy Fountain'],
};

var defaultSpawns = {
  'Child': 'KF Links House',
  'Adult': 'Temple of Time',
};

var defaultSpawns = {
  'Child': 'KF Links House',
  'Adult': 'Temple of Time'
};

function getSpawn(spawnFromLog) {
  var region;
  Object.keys(spawnsByRegion).forEach(function(item) { 
    if(spawnsByRegion[item].includes(spawnFromLog)) {        
      region = item;
    } 
  })
  return region;
}
